---
title: "p8105_hw6_gl2677"
author: "Gaotong LIU"
date: "11/18/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)# cross validation
library(mgcv) # cross validation

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	message = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## Problem 1
```{r load birth data}
birthweight = read_csv("data/birthweight.csv") %>% 
  mutate(babysex = as.factor(babysex),
         frace  = as.factor(frace),
         malform = as.factor(malform),
         mrace = as.factor(mrace))
```

```{r fit regression, include=FALSE}
full_fit = lm(bwt ~ babysex  + blength + gaweeks + 
                   mheight + smoken + wtgain + fincome+ 
                    delwt + malform + parity + 
                bhead +frace + ppbmi + ppwt +
                   menarche + momage + mrace  + 
                pnumlbw + pnumsga ,
            data = birthweight)
anova(full_fit)
initial_fit = lm(bwt ~ babysex + blength + gaweeks + 
                    + bhead + mheight + smoken + wtgain +
                   fincome + delwt + parity +frace + mrace,
            data = birthweight)

my_fit = lm(bwt ~ babysex + blength + gaweeks + bhead,
            data = birthweight)

summary(my_fit)
summary(initial_fit)
summary(full_fit)

```
